import type { Bot } from "@ta/types";

const now = new Date().toISOString();

export const demoBots: Bot[] = [
  {
    id:                       "demo-bot-001",
    user_id:                  "demo-user-00000000-0000-0000-0000-000000000001",
    name:                     "BTC Momentum",
    status:                   "active",
    mode:                     "paper",
    real_trading_enabled:     false,
    requires_manual_approval: false,
    max_open_positions:       3,
    max_position_size_pct:    10,
    risk_per_trade_pct:       1.5,
    max_daily_loss_pct:       3,
    base_currency:            "USDT",
    trading_pairs:            ["BTC/USDT", "ETH/USDT"],
    active_config_id:         null,
    exchange_account_id:      "demo-acct-001",
    trailing_stop_pct:        2,
    is_archived:              false,
    created_at:               now,
    updated_at:               null,
  },
  {
    id:                       "demo-bot-002",
    user_id:                  "demo-user-00000000-0000-0000-0000-000000000001",
    name:                     "ETH Mean Reversion",
    status:                   "paused",
    mode:                     "shadow",
    real_trading_enabled:     false,
    requires_manual_approval: true,
    max_open_positions:       2,
    max_position_size_pct:    5,
    risk_per_trade_pct:       1,
    max_daily_loss_pct:       2,
    base_currency:            "USDT",
    trading_pairs:            ["ETH/USDT"],
    active_config_id:         null,
    exchange_account_id:      "demo-acct-001",
    trailing_stop_pct:        null,
    is_archived:              false,
    created_at:               now,
    updated_at:               null,
  },
  {
    id:                       "demo-bot-003",
    user_id:                  "demo-user-00000000-0000-0000-0000-000000000001",
    name:                     "SOL Breakout (Live Pilot)",
    status:                   "active",
    mode:                     "live",
    real_trading_enabled:     true,
    requires_manual_approval: true,
    max_open_positions:       1,
    max_position_size_pct:    2,
    risk_per_trade_pct:       0.5,
    max_daily_loss_pct:       1,
    base_currency:            "USDT",
    trading_pairs:            ["SOL/USDT"],
    active_config_id:         null,
    exchange_account_id:      "demo-acct-002",
    trailing_stop_pct:        3,
    is_archived:              false,
    created_at:               now,
    updated_at:               null,
  },
];
